swagger: '2.0'
info:
  description: 电脑商城 网站文档 基于jsonp
  version: '1.0'
  title: 电脑商城
  termsOfService: 'http://'
  contact:
    email: 1025155365@qq.com
  license:
    name: 如果是更新版本，在接口的后面都会带上当前的版本号，只需ctrl-f输入当前版本号，即可找到
host: unknown
basePath: /
tags:
  - name: auth
    description: 跟用户权限有关
  - name: school
    description: 跟学校有关  
schemes:
  - https
paths:
  /web/register:
    get:
      tags:
        - auth
      summary: '用户注册 v1.0'
      description: ''
      parameters:
        - in: query
          name: callback
          description: jsonp回调函数
          required: true
          type: string
        - in: query
          name: data
          description: '<b>json字符串，需要urlencoding</b><br/>
          {<br/>
            "school_id": "学校id,必填", <br/>
            "email": "邮箱，与手机号互斥",<br/>
            "phone": "手机号,与邮箱互斥",<br/>
            "password": "密码,必填, 不低于8位",<br/>
            "valid_code" "手机验证码，4位数字，仅当填写手机号时必填"<br/>
          }'
          required: true
          type: string
              
      responses:
        '200':
          description: 'callback_param(<br/>
            {<br>
                "success": "0表示成功，1表示失败",<br/>
                "detail": "失败原因，成功时为空"<br>
            }
          <br/>);'
        '500':
          description: '服务器异常'
          
  /web/login:
    get:
      tags:
        - auth
      summary: '用户登陆 v1.0'
      description: ''
      parameters:
        - in: query
          name: callback
          description: jsonp回调函数
          required: true
          type: string
        - in: query
          name: data
          description: '<b>json字符串，需要urlencoding</b><br/>
          {<br/>
            "email": "邮箱，与手机号互斥",<br/>
            "phone": "手机号,与邮箱互斥",<br/>
            "password": "加密后的密码,必填, md5(email/phone + "shop" + 真实密码)"<br/>
          }'
          required: true
          type: string
              
      responses:
        '200':
          description: 'callback_param(<br/>
            {<br>
                "success": "0表示成功，1表示失败",<br/>
                "detail": "失败原因，成功时为空",<br/>
                "token": "后台返回的token, 用于标识登陆"<br/>
            }
          <br/>);'
        '500':
          description: '服务器异常'
          
  /web/phone_valid_code:
    get:
      tags:
        - auth
      summary: '获取手机验证码 v1.0'
      description: ''
      parameters:
        - in: query
          name: callback
          description: jsonp回调函数
          required: true
          type: string
        - in: query
          name: data
          description: '<b>json字符串，需要urlencoding</b><br/>
          {<br/>
            "phone": "手机号,必填"<br/>
          }'
          required: true
          type: string
              
      responses:
        '200':
          description: 'callback_param(<br/>
            {<br>
                "success": "0表示成功，1表示失败",<br/>
                "detail": "失败原因，成功时为空"<br/>
            }
          <br/>);'
        '500':
          description: '服务器异常'

  /web/reset_pwd/phone:
    get:
      tags:
        - auth
      summary: '重置密码（通过手机号）v1.0'
      description: ''
      parameters:
        - in: query
          name: callback
          description: jsonp回调函数
          required: true
          type: string
        - in: query
          name: data
          description: '<b>json字符串，需要urlencoding</b><br/>
          {<br/>
            "phone": "手机号,必填",<br/>
            "valid_code" "手机验证码，4位数字，仅当填写手机号时必填",<br/>
            "password": "密码"<br/>
          }'
          required: true
          type: string
              
      responses:
        '200':
          description: 'callback_param(<br/>
            {<br>
                "success": "0表示成功，1表示失败",<br/>
                "detail": "失败原因，成功时为空"<br/>
            }
          <br/>);'
        '500':
          description: '服务器异常'
          
  /web/reset_pwd/email:
    get:
      tags:
        - auth
      summary: '重置密码（通过邮箱）v1.0'
      description: '前端在输入邮箱后，点击确认，后台发送邮件，点击邮件中的链接，如
      http://xxx.com?code=xxx，该链接将跳到前端的重置密码的页面，需要输入密码'
      parameters:
        - in: query
          name: callback
          description: jsonp回调函数
          required: true
          type: string
        - in: query
          name: data
          description: '<b>json字符串，需要urlencoding</b><br/>
          {<br/>
            "code": "校验码，由邮件中的链接提供",<br/>
            "password": "密码"<br/>
          }'
          required: true
          type: string
              
      responses:
        '200':
          description: 'callback_param(<br/>
            {<br>
                "success": "0表示成功，1表示失败",<br/>
                "detail": "失败原因，成功时为空"<br/>
            }
          <br/>);'
        '500':
          description: '服务器异常'        
          
  /web/school/search:
    get:
      tags:
        - school
      summary: '学校搜索 v1.0'
      description: '用于注册时选择学校'
      parameters:
        - in: query
          name: callback
          description: jsonp回调函数
          required: true
          type: string
        - in: query
          name: data
          description: '<b>json字符串，需要urlencoding</b><br/>
          {<br/>
            "keyword": "关键字，必填"<br/>
          }'
          required: true
          type: string
              
      responses:
        '200':
          description: 'callback_param(<br/>
            {<br>
                "success": "0表示成功，1表示失败",<br/>
                "detail": "失败原因，成功时为空",<br/>
                "data": [<br/>{<br/>
                  "id": "学校id",<br/>
                  "name": "学校名称"<br/>
                }<br/> ... 
                ]<br/>
            }
          <br/>);'
        '500':
          description: '服务器异常'                